FROM oven/bun:1 AS base

FROM base AS builder
WORKDIR /app
RUN bun install -g turbo
COPY . .
RUN turbo prune bot --docker

FROM base AS installer
WORKDIR /app

# First install dependencies (as they change less often)
COPY --from=builder /app/out/json/ .
RUN pnpm install --frozen-lockfile

# Build the project and its dependencies
COPY --from=builder /app/out/full/ .
# Since bot doesn't have a build step, we'll just run typecheck
RUN bun run turbo typecheck --filter=bot

FROM base AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 discordbot
RUN adduser --system --uid 1001 discordbot
USER discordbot

COPY --from=installer /app .

# Pass DATABASE_URL as build arg and set as env var
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ENV NODE_ENV=production

CMD ["bun", "run", "start"]