import type { Metadata } from "next";
import "./globals.css";
import { questrial } from "../styles/fonts";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.variable} font-sans antialiased bg-[#fefcf6] px-2`}>
        {children}
      </body>
    </html>
  );
}
