import type { Metadata } from "next";
import "./globals.css";
import { funnelSans, satoshi as satoshiFont } from "../styles/fonts";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelSans.variable} font-sans antialiased`}
      >
        <div className="border-b border-x border-neutral-300">
          <div className="max-w-screen-xl border-x border-neutral-300 mx-auto p-2 px-4">
            <Link href="/" className="text-xl text-black">Velumn</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
