import type { Metadata } from 'next';
import './globals.css';
import { funnelSans } from '../styles/fonts';
import { getCurrentUser } from '@/server/user';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const data = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${funnelSans.variable} font-sans antialiased`}>

        {children}
      </body>
    </html>
  );
}
