/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardServersIndexRouteImport } from './routes/_dashboard/servers/index'
import { Route as DashboardServersNewRouteImport } from './routes/_dashboard/servers/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardServersServerIdIndexRouteImport } from './routes/_dashboard/servers/$serverId/index'
import { Route as DashboardServersServerIdChannelsRouteImport } from './routes/_dashboard/servers/$serverId/channels'
import { Route as DashboardServersServerIdPublishingRouteImport } from './routes/_dashboard/servers/$serverId/publishing'
import { Route as DashboardServersServerIdSetupRouteImport } from './routes/_dashboard/servers/$serverId/setup'
import { Route as DashboardServersServerIdThreadsRouteImport } from './routes/_dashboard/servers/$serverId/threads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServersIndexRoute = DashboardServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersNewRoute = DashboardServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServersServerIdIndexRoute =
  DashboardServersServerIdIndexRouteImport.update({
    id: '/servers/$serverId/',
    path: '/servers/$serverId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServersServerIdChannelsRoute =
  DashboardServersServerIdChannelsRouteImport.update({
    id: '/servers/$serverId/channels',
    path: '/servers/$serverId/channels',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServersServerIdPublishingRoute =
  DashboardServersServerIdPublishingRouteImport.update({
    id: '/servers/$serverId/publishing',
    path: '/servers/$serverId/publishing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServersServerIdSetupRoute =
  DashboardServersServerIdSetupRouteImport.update({
    id: '/servers/$serverId/setup',
    path: '/servers/$serverId/setup',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServersServerIdThreadsRoute =
  DashboardServersServerIdThreadsRouteImport.update({
    id: '/servers/$serverId/threads',
    path: '/servers/$serverId/threads',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/servers/new': typeof DashboardServersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/servers/': typeof DashboardServersIndexRoute
  '/servers/$serverId/channels': typeof DashboardServersServerIdChannelsRoute
  '/servers/$serverId/publishing': typeof DashboardServersServerIdPublishingRoute
  '/servers/$serverId/setup': typeof DashboardServersServerIdSetupRoute
  '/servers/$serverId/threads': typeof DashboardServersServerIdThreadsRoute
  '/servers/$serverId/': typeof DashboardServersServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/servers/new': typeof DashboardServersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/servers': typeof DashboardServersIndexRoute
  '/servers/$serverId/channels': typeof DashboardServersServerIdChannelsRoute
  '/servers/$serverId/publishing': typeof DashboardServersServerIdPublishingRoute
  '/servers/$serverId/setup': typeof DashboardServersServerIdSetupRoute
  '/servers/$serverId/threads': typeof DashboardServersServerIdThreadsRoute
  '/servers/$serverId': typeof DashboardServersServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/_dashboard/servers/new': typeof DashboardServersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/servers/': typeof DashboardServersIndexRoute
  '/_dashboard/servers/$serverId/channels': typeof DashboardServersServerIdChannelsRoute
  '/_dashboard/servers/$serverId/publishing': typeof DashboardServersServerIdPublishingRoute
  '/_dashboard/servers/$serverId/setup': typeof DashboardServersServerIdSetupRoute
  '/_dashboard/servers/$serverId/threads': typeof DashboardServersServerIdThreadsRoute
  '/_dashboard/servers/$serverId/': typeof DashboardServersServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/servers/new'
    | '/api/auth/$'
    | '/servers/'
    | '/servers/$serverId/channels'
    | '/servers/$serverId/publishing'
    | '/servers/$serverId/setup'
    | '/servers/$serverId/threads'
    | '/servers/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/servers/new'
    | '/api/auth/$'
    | '/servers'
    | '/servers/$serverId/channels'
    | '/servers/$serverId/publishing'
    | '/servers/$serverId/setup'
    | '/servers/$serverId/threads'
    | '/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth/sign-in'
    | '/_dashboard/servers/new'
    | '/api/auth/$'
    | '/_dashboard/servers/'
    | '/_dashboard/servers/$serverId/channels'
    | '/_dashboard/servers/$serverId/publishing'
    | '/_dashboard/servers/$serverId/setup'
    | '/_dashboard/servers/$serverId/threads'
    | '/_dashboard/servers/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/servers/': {
      id: '/_dashboard/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof DashboardServersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers/new': {
      id: '/_dashboard/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof DashboardServersNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/servers/$serverId/': {
      id: '/_dashboard/servers/$serverId/'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof DashboardServersServerIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers/$serverId/channels': {
      id: '/_dashboard/servers/$serverId/channels'
      path: '/servers/$serverId/channels'
      fullPath: '/servers/$serverId/channels'
      preLoaderRoute: typeof DashboardServersServerIdChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers/$serverId/publishing': {
      id: '/_dashboard/servers/$serverId/publishing'
      path: '/servers/$serverId/publishing'
      fullPath: '/servers/$serverId/publishing'
      preLoaderRoute: typeof DashboardServersServerIdPublishingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers/$serverId/setup': {
      id: '/_dashboard/servers/$serverId/setup'
      path: '/servers/$serverId/setup'
      fullPath: '/servers/$serverId/setup'
      preLoaderRoute: typeof DashboardServersServerIdSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers/$serverId/threads': {
      id: '/_dashboard/servers/$serverId/threads'
      path: '/servers/$serverId/threads'
      fullPath: '/servers/$serverId/threads'
      preLoaderRoute: typeof DashboardServersServerIdThreadsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardServersNewRoute: typeof DashboardServersNewRoute
  DashboardServersIndexRoute: typeof DashboardServersIndexRoute
  DashboardServersServerIdChannelsRoute: typeof DashboardServersServerIdChannelsRoute
  DashboardServersServerIdPublishingRoute: typeof DashboardServersServerIdPublishingRoute
  DashboardServersServerIdSetupRoute: typeof DashboardServersServerIdSetupRoute
  DashboardServersServerIdThreadsRoute: typeof DashboardServersServerIdThreadsRoute
  DashboardServersServerIdIndexRoute: typeof DashboardServersServerIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardServersNewRoute: DashboardServersNewRoute,
  DashboardServersIndexRoute: DashboardServersIndexRoute,
  DashboardServersServerIdChannelsRoute: DashboardServersServerIdChannelsRoute,
  DashboardServersServerIdPublishingRoute:
    DashboardServersServerIdPublishingRoute,
  DashboardServersServerIdSetupRoute: DashboardServersServerIdSetupRoute,
  DashboardServersServerIdThreadsRoute: DashboardServersServerIdThreadsRoute,
  DashboardServersServerIdIndexRoute: DashboardServersServerIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
