name: ci
on:
  push:
    branches:
      - main
  pull_request:
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency: ci-build-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install Packages
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
  lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency: ci-lint-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install Packages
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint
  test:
    name: Type Check and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency: ci-test-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install Packages
        run: bun install --frozen-lockfile

      - name: Type Check
        run: bun run type-check

      - name: Test
        run: bun run test
